import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Utilities/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Day 33",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} suppressContentEditableWarning={true}>
      <Navbar/>
        {children}</body>
    </html>
  );
}
